### ISSUE TITLE
INSERT DOESN'T WORK

### ISSUE THREAD

**Issue by sphratrioth666** [ManlyMarco/Koikatu-Gameplay-Mod#3]
After updating and applying all the mods/HF with a newest version, I can't force INSERT ANAL. I don't know if it's on purpose that you decided to limit force to normal intercourse but I remember that forcing ANAL had been possible in past (before updating and installing last DLCs). Thanks, greetings and thanx for your great work.

**Comment by ManlyMarco** [comment]
Fixed in latest release
