### ISSUE TITLE
Pregnancy Morphs revert on entering H-Scenes or Editor

### ISSUE THREAD

**Issue by Rivvik** [ManlyMarco/Koikatu-Gameplay-Mod#4]
Every time I enter an H-scene with a girl who is visibly pregnant on the overmap, has her form reverted to her default a little after loading the H-scene or Editor screen. All my plugins are up to date. The really odd thing is, she will start the scene correctly then revert after a few seconds

**Comment by ManlyMarco** [comment]
This seems to happen because of kplug. Can you test with it removed?

**Comment by Rivvik** [comment]
Yup that was it.
